minimumReleaseAge: 20160
shamefullyHoist: true
overrides:
  "@intlify/message-compiler": ^11.1.2
  form-data@4.0.2: 4.0.5
  koa@2.15.3: 2.16.3
allowBuilds:
  esbuild: false
  maplibre-gl: false
  simple-git-hooks: false
  vue-demi: false
  workerd: false
